# This is the network config written by 'subiquity'
network:
  ethernets:
    ens160:
      dhcp4: true
      nameservers:
        addresses:
          - 172.31.253.49
        search:
          - epifood.local
  version: 2